
# ===== TownyMobs Config =====

# Sets the model of the mobs. Can be 0 (skeleton), 1 (zombie) or 2 (pigzombie)
model: 2

# Sets the maximum number of towny mobs that can spawn 
# No monsters will naturally spawn if there are too many
spawnLimit: 60

# Attack naturally spawning hostile mobs
attackMobs: true

# Since vanilla zombies don't attack back, this will decide
# whether or not towny mobs will attack zombies.
# Only works when attackMobs is enabled.
attackZombies: true

# Prevent mobs from damaging friendly players and mobs
noFriendlyFire: true

# Attacking a town resident or towny mob will agro their nearby towny mobs
alertAllies: true

# Enabling this option will allow players to heal their mobs for a set amount of health
# by right clicking them with an apple
feedEnabled: true
feedAmount: 5

# Set the maximum number of mobs a town can spawn, regardless of power
# (0 = no limit)
mobsPerTown: 0

# Display the mob's town name above the mob (in yellow)
displayMobTown: true

# Set the normal movement speed of the mobs (Recommend between .3 and .5, default .3)
mobSpeed: .3

# Set the speed of the mobs when patroling (Recommend between .175 and .3, default .175)
mobPatrolSpeed: .175

# Set the distance the mobs will attempt to pathfind (Recommend between 16 and 64, default 64)
mobNavRange: 64

# Enables the use of /tmc, a command designed to be used by command blocks
tmcEnabled: true

# Excludes towny mobs from kill commands such as /killall (experimental)
# Set this to false if runKeepAliveTask is enabled
excludeFromKillCommands: false

# Prevents towny mobs from being killed by other plugins (Warning: Experimental, may cause lag)
runKeepAliveTask: false

# === Mob Specific Config ===

# Allowed to spawn, disabling does not remove existing mobs
Archer.enabled: true
# Health
Archer.maxHp: 20
# Custom damage, set to 0 to use default damage (normal damage is 2)
Archer.damage: 0
# Town power spent upon spawning this mob (power = maximum number of plots)
Archer.powerCost: 4.0
# Money spent upon spawning this mob, requires Vault
Archer.moneyCost: 0.0
# Experimental, you can specify 1 item for this mob to drop. (Item ID)
Archer.drops: 0

Mage.enabled: true
Mage.maxHp: 20
# Mage damage not modifiable
Mage.powerCost: 6.0
Mage.moneyCost: 0.0
Mage.drops: 0

Swordsman.enabled: true
Swordsman.maxHp: 20
# Normal damage is 5
Swordsman.damage: 0
Swordsman.powerCost: 5.0
Swordsman.moneyCost: 0.0
Swordsman.drops: 0

Titan.enabled: true
Titan.maxHp: 40
# Normal damage is 15
Titan.damage: 0
Titan.powerCost: 11.0
Titan.moneyCost: 0.0
Titan.drops: 0

# === Auto-Save Options ===

# Enable periodic saving in case of server crash
autoSave: false

# Server ticks between each save (20 Ticks = 1 Second)
# This should be set the same as autosave in your bukkit.yml file
# or the same as any world auto-save plugin you are using.
saveInterval: 6000
