name: TownyMobs
main: com.gmail.scyntrus.tmob.TownyMobs
author: Scyntrus
version: 2.7.4_v1_7_R2
depend: [Towny]
softdepend: [Vault]
commands:
    tm:
        description: Towny mobs control
        usage: "/tm [spawn|order|color] [parameters]"
        aliases: tmob
    tmc:
        description: Spawn a mob to a specific town. Designed to be used by command blocks
        usage: "/tmc MOBTYPE TOWNNAME WORLDNAME X Y Z [EXTRAINFO]"
permissions:
    tmob.spawn:
        description: Allows you to use /tm spawn with all mobs
        default: true
    tmob.spawn.archer:
        description: Allows you to use /tm spawn archer
        default: false
    tmob.spawn.mage:
        description: Allows you to use /tm spawn mage
        default: false
    tmob.spawn.swordsman:
        description: Allows you to use /tm spawn swordsman
        default: false
    tmob.spawn.titan:
        description: Allows you to use /tm spawn titan
        default: false
    tmob.color:
        description: Allows you to use /tm color
        default: true
    tmob.order:
        description: Allows you to use /tm order
        default: true
    tmob.order.move:
        description: Allows you to use /tm order moveToPoint
        default: true
    tmob.order.tp:
        description: Allows you to use /tm order [tpSpawn|tpHere]
        default: op
    tmob.bypass:
        description: Allows you to spawn mobs without restriction
        default: false
    tmob.tmc:
        description: Allows you to use /tmc, a command designed for command blocks
        default: false
    tmob.selectall:
        description: Allows you to use /tm selectall
        default: op
    